package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import model.DatbaseSt;
public class FXMLDocumentController {
	@FXML
	private Button button;
	@FXML
	private Label label;
	@FXML
	private TextField tf1;
	@FXML
	private TextField tf2;

	// Event Listener on Button[#button].onAction
	@FXML
	public void handleButtonAction(ActionEvent event)  {
		// TODO Autogenerated
		DatbaseSt st= new DatbaseSt();
    	//int id=Integer.parseInt(tf1.getText());
    	
    	ResultSet rt =st.listRecGames();
    	try {
			while (rt.next()) {
				System.out.println(rt.getString(3));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

 	
 	
	}
}
