package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.event.ActionEvent;

public class ServerFXMLController {
	@FXML
	private Button btn1;
	private Label labl;

	// Event Listener on Button[#btn1].onAction
	@FXML
	public void handleButtonAction(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("clicked");
		//labl.setText("hello");
	}
}
